# Generated by Django 3.2.10 on 2023-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь покупателя', 'verbose_name_plural': 'Обратная связь покупателя'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_email',
            field=models.EmailField(max_length=254, verbose_name='Почта покупателя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_message',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(max_length=50, verbose_name='Имя покупателя'),
        ),
    ]
