# Generated by Django 3.2.10 on 2023-03-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20230316_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.shippingaddress'),
            preserve_default=False,
        ),
    ]
