# Generated by Django 3.2.10 on 2023-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_tag_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Новая цена'),
        ),
    ]
